apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Recycle
  hostPath:
    # path: "/c/Users/Maarten/OneDrive - morinsights.nl/Documents/GitHub/flask_AZfunction/PostgreSQL/data"
    # path: /c/Users/Maarten/"OneDrive - morinsights.nl"/Documents/GitHub/flask_AZfunction/PostgreSQL/data
    path: /data/postgresql